services:
  a.x:
    build:
      context: .
      dockerfile: Dockerfile.A.X
    container_name: a.x
    entrypoint: [ "python3", "mcp_vllm.py" ]
    image: ax-vllm:latest
    ports:
      - "8000:4200"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    volumes:
      - /home/vsc/LLM/model:/models
      - /home/vsc/LLM_TUNE/QA-FineTune/log:/app/log
      - /home/vsc/LLM_TUNE/QA-FineTune/main:/app
      - /home/vsc/LLM_TUNE/QA-FineTune/docker/mcp_vllm.py:/app/mcp_vllm.py
    environment:
      - MODEL_BASE_DIR=/models
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING=UTF-8
      - MCP_PORT=4200
      - VLLM_USE_V1=0
    ipc: host
  exaone:
    build:
      context: .
      dockerfile: Dockerfile.Exaone
    container_name: exaone
    entrypoint: [ "python3", "mcp_vllm.py" ]
    image: exaone-vllm:latest
    ports:
      - "8001:4200"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    volumes:
      - /home/vsc/LLM/model:/models
      - /home/vsc/LLM_TUNE/QA-FineTune/log:/app/log
      - /home/vsc/LLM_TUNE/QA-FineTune/main:/app
      - /home/vsc/LLM_TUNE/QA-FineTune/docker/mcp_vllm.py:/app/mcp_vllm.py
    environment:
      - MODEL_BASE_DIR=/models
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING=UTF-8
      - MCP_PORT=4200
      - VLLM_USE_V1=0
    ipc: host
