FROM vllm/vllm-openai:cu130-nightly-x86_64
ENTRYPOINT []
WORKDIR /app
COPY requirements_exaone.txt .
RUN pip install --no-cache-dir -r requirements_exaone.txt
COPY mcp_vllm.py .
ENV VLLM_ALLOW_RUNTIME_LORA_UPDATING=True
